### ISSUE TITLE
New version of td-agent breaks monitoring build

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#1096]
On vm4:

```
================================================================================[0m
[31mError executing action `restart` on resource 'service[td-agent]'[0m
================================================================================[0m

[0mMixlib::ShellOut::ShellCommandFailed[0m
------------------------------------[0m
Expected process to exit with [0], but received '1'
[0m---- Begin output of /etc/init.d/td-agent stop ----
[0mSTDOUT: Stopping td-agent:  * td-agent
[0mSTDERR: 
[0m---- End output of /etc/init.d/td-agent stop ----
[0mRan /etc/init.d/td-agent stop returned 1[0m
```

https://docs.treasuredata.com/articles/td-agent-changelog

**Comment by kamidzi** [comment]
Lovely; this only seems to manifest during build.

**Comment by erhudy** [comment]
In `/var/log/td-agent/td-agent.log`:
```
2016-07-21 21:07:29 +0000 [error]: unexpected error error_class=Errno::EADDRINUSE error=#<Errno::EADDRINUSE: Address already in use - listen(2)>
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_http.rb:104:in `initialize'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_http.rb:104:in `new'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/plugin/in_http.rb:104:in `start'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/root_agent.rb:115:in `block in start'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/root_agent.rb:114:in `each'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/root_agent.rb:114:in `start'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:237:in `start'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/engine.rb:187:in `run'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:570:in `run_engine'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:162:in `block in start'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in `call'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:366:in `main_process'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:339:in `block in supervise'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in `fork'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:338:in `supervise'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/supervisor.rb:156:in `start'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.26/bin/fluentd:5:in `<top (required)>'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `load'
  2016-07-21 21:07:29 +0000 [error]: /opt/td-agent/embedded/bin/fluentd:23:in `<top (required)>'
  2016-07-21 21:07:29 +0000 [error]: /usr/sbin/td-agent:7:in `load'
  2016-07-21 21:07:29 +0000 [error]: /usr/sbin/td-agent:7:in `<main>'
```

When I restarted it manually with `service td-agent start`, it started right up.
