### ISSUE TITLE
rally failure breaks build

### ISSUE THREAD

**Issue by furlongm** [bloomberg/chef-bcpc#1281]
The rally failure below breaks the builds.

If there could be a flag to optionally build rally, we could avoid this (and speedup builds that won't use it).

For the actual failure below, perhaps a requirements.txt is needed to pin the pip package versions?

```
Recipe: bcpc::rally-deployments
  * bash[rally-deployment-create-v2.0] action run
    
    ================================================================================
    Error executing action `run` on resource 'bash[rally-deployment-create-v2.0]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20170920-17096-1tyx0pq" ----
    STDOUT: Command failed, please check log for more info
    2017-09-20 23:37:28.018 23265 CRITICAL rally [-] ImportError: cannot import name VariableManager
    2017-09-20 23:37:28.018 23265 ERROR rally Traceback (most recent call last):
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/bin/rally", line 11, in <module>
    2017-09-20 23:37:28.018 23265 ERROR rally     sys.exit(main())
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/rally/cli/main.py", line 38, in main
    2017-09-20 23:37:28.018 23265 ERROR rally     return cliutils.run(sys.argv, categories)
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/rally/cli/cliutils.py", line 661, in run
    2017-09-20 23:37:28.018 23265 ERROR rally     ret = fn(*fn_args, **fn_kwargs)
    2017-09-20 23:37:28.018 23265 ERROR rally   File "<decorator-gen-5>", line 2, in create
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/rally/plugins/__init__.py", line 42, in ensure_plugins_are_loaded
    2017-09-20 23:37:28.018 23265 ERROR rally     load()
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/rally/plugins/__init__.py", line 32, in load
    2017-09-20 23:37:28.018 23265 ERROR rally     discover.import_modules_from_package("rally.plugins")
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/rally/common/plugin/discover.py", line 60, in import_modules_from_package
    2017-09-20 23:37:28.018 23265 ERROR rally     module_name)
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/oslo_utils/importutils.py", line 73, in import_module
    2017-09-20 23:37:28.018 23265 ERROR rally     __import__(import_str)
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/rally/plugins/openstack/hook/fault_injection.py", line 16, in <module>
    2017-09-20 23:37:28.018 23265 ERROR rally     import os_faults
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/os_faults/__init__.py", line 21, in <module>
    2017-09-20 23:37:28.018 23265 ERROR rally     from os_faults.ansible import executor
    2017-09-20 23:37:28.018 23265 ERROR rally   File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/os_faults/ansible/executor.py", line 24, in <module>
    2017-09-20 23:37:28.018 23265 ERROR rally     from ansible.vars import VariableManager
    2017-09-20 23:37:28.018 23265 ERROR rally ImportError: cannot import name VariableManager
    2017-09-20 23:37:28.018 23265 ERROR rally
    STDERR: 
    ---- End output of "bash"  "/tmp/chef-script20170920-17096-1tyx0pq" ----
    Ran "bash"  "/tmp/chef-script20170920-17096-1tyx0pq" returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc/recipes/rally-deployments.rb
    
     72:   bash "rally-deployment-create-#{version}" do
     73:       user rally_user
     74:       code <<-EOH
     75:           # Another approach is to use --fromenv...
     76:           source #{rally_venv_dir}/bin/activate
     77:           rally deployment create --filename="#{infile}" --name=#{version}
     78:       EOH
     79:   end
     80: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/bcpc/recipes/rally-deployments.rb:72:in `block in from_file'
    
    bash("rally-deployment-create-v2.0") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      command "rally-deployment-create-v2.0"
      backup 5
      returns 0
      user "vagrant"
      code "          # Another approach is to use --fromenv...\n          source /home/vagrant/rally/venv/bin/activate\n          rally deployment create --filename=\"/var/chef/cache/rally-existing-v2.0.json\" --name=v2.0\n"
      interpreter "bash"
      declared_type :bash
      cookbook_name "bcpc"
      recipe_name "rally-deployments"
    end
    
    Platform:
    ---------
    x86_64-linux
```

**Comment by srsakhamuri** [comment]
Fixes partially with this commit: https://github.com/bloomberg/chef-bcpc/commit/201f91500b9d78c3b84add6319127966e5254844

**Comment by kamidzi** [comment]
@srsakhamuri : this is fixed, no?

**Comment by srsakhamuri** [comment]
It will be once we merge the PR #1298

**Comment by srsakhamuri** [comment]
This issue is fixed!
