### ISSUE TITLE
Rally recipe broken on 6.4.3 Linux build when building behind proxy

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#1326]
When building behind proxy, pip encounters ssl certificate errors. During build:

```
  * bash[install-rally] action run

    ================================================================================
    Error executing action `run` on resource 'bash[install-rally]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20180109-12982-ap6vm7" ----
    STDOUT: Collecting pbr
      Could not fetch URL https://pypi.python.org/simple/pbr/: There was a problem confirming the ssl certificate: [Errno 1] _s
sl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed - skipping
    Collecting rally==0.9.1
```

This is confirmed by jumping on the the bootstrap node:
```
vagrant@bcpc-vm-bootstrap:~$ strace -eopen -f /home/vagrant/rally/venv/bin/pip search -v rally
<...>
Exception:
Traceback (most recent call last):
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/commands/search.py", line 45, in run
    pypi_hits = self.search(query, options)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/commands/search.py", line 62, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/download.py", line 775, in request
    headers=headers, stream=True)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
<...>
/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
open("/home/vagrant/rally/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/cacert.pem", O_RDONLY) = 4
```

**Comment by kamidzi** [comment]
WONTFIX
