### ISSUE TITLE
Multiple tenants broken in 5.x due to dhcp_server nova_network bug

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#573]
In local tests w/Trusty+Kilo, `nova-network` creates the `dhcp_server` setting with an invalid value - it's in the wrong subnet.  This causes machines in a non-default tenancy not to receive its DHCP address as the dnsmasq's `listen-address` is what the associated bridge is listening on (e.g., `br1001` should listen on 1.127.1.1, but is listening instead on 1.127.0.1).  Chaos ensues.

I have not fully tracked down where the specific issue is - it's likely in the `nova-manage` call that we have in `nova-setup.rb`:

```
nova-manage network create --label fixed --fixed_range_v4=#{node['bcpc']['fixed']['cidr']} --num_networks=#{node['bcpc']['fixed']['num_networks']} --multi_host=T --network_size=#{node['bcpc']['fixed']['network_size']} --vlan_start=#{node['bcpc']['fixed']['vlan_start']} --bridge_interface=#{node['bcpc']['fixed']['vlan_interface']}
```

I will bet that the `fixed_range_v4` code path sets `gateway` properly, but doesn't update `dhcp_server` accordingly.

IOW, the `dhcp_server` value is like:

```
mysql> select id, gateway, dhcp_server from networks where id=2;
+----+-----------+-------------+
| id | gateway   | dhcp_server |
+----+-----------+-------------+
|  2 | 1.127.1.1 | 1.127.0.1   |
+----+-----------+-------------+
1 row in set (0.00 sec)
```

The hacky workaround is:

```
mysql> update networks set dhcp_server='1.127.1.1' where id=2;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select id, gateway, dhcp_server from networks where id=2;
+----+-----------+-------------+
| id | gateway   | dhcp_server |
+----+-----------+-------------+
|  2 | 1.127.1.1 | 1.127.1.1   |
+----+-----------+-------------+
1 row in set (0.01 sec)
```

Clearing out the bridges, killing `dnsmasq`, and restarting `nova-network` after that change suffices.

**Comment by erhudy** [comment]
Was able to reproduce the issue; the reason it wasn't discovered earlier is because it doesn't happen until you have at least 3 tenants, and probably I only tried launching instances off a single non-admin tenant. Setting `dhcp_server` manually in MySQL fixed the issue.

Information for anyone else who encounters the problem: instances will fail to spawn in Horizon with an unknown error, and in `nova-compute.log` on the host the instance was scheduled for, Nova will barf out a big traceback that looks like this:
```
2015-05-18 13:13:21.313 25737 ERROR nova.compute.manager [-] Instance failed network setup after 1 attempt(s)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager Traceback (most recent call last):
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1770, in _allocate_network_async
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     dhcp_options=dhcp_options)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/nova/network/api.py", line 49, in wrapped
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     return func(self, context, *args, **kwargs)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/nova/network/base_api.py", line 64, in wrapper
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     res = f(self, context, *args, **kwargs)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/nova/network/api.py", line 281, in allocate_for_instance
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     nw_info = self.network_rpcapi.allocate_for_instance(context, **args)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/nova/network/rpcapi.py", line 152, in allocate_for_instance
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     macs=jsonutils.to_primitive(macs))
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/client.py", line 156, in call
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     retry=self.retry)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/oslo_messaging/transport.py", line 90, in _send
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     timeout=timeout, retry=retry)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/oslo_messaging/_drivers/amqpdriver.py", line 350, in send
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     retry=retry)
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager   File "/usr/lib/python2.7/dist-packages/oslo_messaging/_drivers/amqpdriver.py", line 341, in _send
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager     raise result
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager RemoteError: Remote error: ProcessExecutionError Unexpected error while running command.
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager Command: sudo nova-rootwrap /etc/nova/rootwrap.conf env CONFIG_FILE=["/etc/nova/nova.conf"] NETWORK_ID=2 dnsmasq --strict-order --bind-interfaces --conf-file= --pid-file=/var/lib/nova/networks/nova-br1001.pid --dhcp-optsfile=/var/lib/nova/networks/nova-br1001.opts --listen-address=1.100.0.1 --except-interface=lo --dhcp-range=set:fixed_1,1.100.0.131,static,255.255.255.128,120s --dhcp-lease-max=128 --dhcp-hostsfile=/var/lib/nova/networks/nova-br1001.conf --dhcp-script=/usr/bin/nova-dhcpbridge --no-hosts --leasefile-ro --domain=ll21.bcpc.bloomberg.com --addn-hosts=/var/lib/nova/networks/nova-br1001.hosts
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager Exit code: 2
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager Stdout: u''
2015-05-18 13:13:21.313 25737 TRACE nova.compute.manager Stderr: u'No handlers could be found for logger "oslo_config.cfg"\n2015-05-18 13:13:20.013 16828 INFO oslo_messaging._drivers.impl_rabbit [req-0af87e13-5521-41aa-9edc-ce6c860b6b3c - - - - -] Connecting to AMQP server on 192.168.194.45:5672\n2015-05-18 13:13:20.027 16828 INFO oslo_messaging._drivers.impl_rabbit [req-0af87e13-5521-41aa-9edc-ce6c860b6b3c - - - - -] Connected to AMQP server on 192.168.194.45:5672\n2015-05-18 13:13:20.064 16828 INFO oslo_messaging._drivers.impl_rabbit [req-0af87e13-5521-41aa-9edc-ce6c860b6b3c - - - - -] Connecting to AMQP server on 192.168.194.45:5672\n2015-05-18 13:13:20.082 16828 INFO oslo_messaging._drivers.impl_rabbit [req-0af87e13-5521-41aa-9edc-ce6c860b6b3c - - - - -] Connected to AMQP server on 192.168.194.45:5672\n2015-05-18 13:13:21.199 16828 ERROR oslo_messaging._drivers.impl_rabbit [-] Failed to consume message from queue: \n\ndnsmasq: failed to create listening socket for 1.100.0.1: Address already in use\n'
```

**Comment by erhudy** [comment]
Found the logic in nova/network/manager.py that handles this. In the event that a DHCP server is not provided, it is supposed to set the DHCP server address to the gateway, but a little println debugging has demonstrated that this doesn't quite work as expected:

```
2015-05-18 14:14:21.701 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] _do_create_networks got following dhcp server: None
2015-05-18 14:14:21.977 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] gateway is now: 1.102.0.1
2015-05-18 14:14:21.977 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] dhcp server is now: 1.102.0.1
2015-05-18 14:14:22.071 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] gateway is now: 1.102.0.129
2015-05-18 14:14:22.072 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] dhcp server is now: 1.102.0.1
2015-05-18 14:14:22.168 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] gateway is now: 1.102.1.1
2015-05-18 14:14:22.169 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] dhcp server is now: 1.102.0.1
2015-05-18 14:14:22.261 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] gateway is now: 1.102.1.129
2015-05-18 14:14:22.261 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] dhcp server is now: 1.102.0.1
[...]
2015-05-18 14:14:23.420 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] gateway is now: 1.102.7.129
2015-05-18 14:14:23.421 23610 WARNING nova.network.manager [req-616f046b-fa96-4550-ab84-c57cf8c8f79a - - - - -] dhcp server is now: 1.102.0.1
```

**Comment by erhudy** [comment]
What's happening is this: the manager enumerates all subnets (in this case, since we're requesting some number of subnets to be created via `nova-manage`, it explodes those into subnets and walks through them). If `dhcp_server` is *None*, it sets `dhcp_server` to the gateway, creates the subnet, and starts the loop over. Since `dhcp_server` was a variable that was already scoped outside the loop, it is now the value of the gateway from the first iteration of the loop, isn't *None* any more, and so the DHCP server for every subnet is set to the gateway of the first subnet.

I don't know if this was by design, but it seems like a flaw to me. Fixing it to use a local variable was trivial and results in the desired behavior:
```
2015-05-18 14:19:50.645 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] _do_create_networks got following dhcp server: None
2015-05-18 14:19:50.915 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] gateway is now: 1.103.0.1
2015-05-18 14:19:50.916 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] dhcp server is now: 1.103.0.1
2015-05-18 14:19:50.969 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] gateway is now: 1.103.0.129
2015-05-18 14:19:50.969 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] dhcp server is now: 1.103.0.129
2015-05-18 14:19:51.026 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] gateway is now: 1.103.1.1
2015-05-18 14:19:51.027 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] dhcp server is now: 1.103.1.1
2015-05-18 14:19:51.080 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] gateway is now: 1.103.1.129
2015-05-18 14:19:51.080 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] dhcp server is now: 1.103.1.129
2015-05-18 14:19:51.143 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] gateway is now: 1.103.2.1
2015-05-18 14:19:51.143 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] dhcp server is now: 1.103.2.1
2015-05-18 14:19:51.195 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] gateway is now: 1.103.2.129
2015-05-18 14:19:51.195 27317 WARNING nova.network.manager [req-150b77e9-2d47-40df-ae4a-153ed8e88c1c - - - - -] dhcp server is now: 1.103.2.129
[...]
```

**Comment by erhudy** [comment]
Filed https://bugs.launchpad.net/nova/+bug/1456321 upstream. I will patch manager.py locally.
