### ISSUE TITLE
Python dependency issues in rally setup completion

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#582]
Now I'm getting the following during the stack bring-up.
```
Successfully installed rally python-novaclient fixtures paramiko boto oslo.utils oslo.serialization SQLAlchemy oslo.i18n simplejson oslo.config netaddr python-neutronclient reque
sts python-zaqarclient python-swiftclient ordereddict oslo.log python-troveclient sphinx PrettyTable Jinja2 python-subunit Babel jsonschema python-cinderclient python-glanceclient PyYAML psycopg2 iso8601 python-heatclient pbr six python-ceilometerclient oslo.db python-saharaclient decorator python-designateclient python-keystoneclient python-ironicclient argparse testtools pycrypto ecdsa netifaces pytz msgpack-python stevedore cliff futures oslo.context Pygments docutils markupsafe extras pyOpenSSL warlock alembic testscenarios testresources sqlalchemy-migrate httplib2 lxml anyjson python-mimeparse traceback2 unittest2 pyparsing cmd2 cryptography jsonpatch Mako Tempita sqlparse linecache2 idna pyasn1 setuptools enum34 ipaddress cffi jsonpointer pycparser
Cleaning up...
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

**Comment by cloudm2** [comment]
Just glancing,  it looks like an issue with pip or a dependencie is missing. I have seen issues like this with our build and timing with the network. Try the build process again.

**Comment by erhudy** [comment]
I just started a build at home and hit the same problem. Scrolling through the build results, here are the problem areas:

This one isn't fatal, but including it for completeness' sake since it's pretty easily resolvable by installing the dev package for libyaml:
```
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
```

This definitely looks fatal:
```
  Running setup.py install for sqlparse
    changing mode of build/scripts-2.7/sqlformat from 644 to 755
    
    changing mode of /usr/local/bin/sqlformat to 755
Compiling /tmp/pip_build_root/linecache2/linecache2/tests/inspect_fodder2.py ...
  File "/tmp/pip_build_root/linecache2/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax
```

**Comment by erhudy** [comment]
It looks like this is because IncompleteRead was removed from requests in 2.4.0, according to this GitHub issue:

https://github.com/tweepy/tweepy/issues/501

**Comment by erhudy** [comment]
I think what we'll need to do is either manually package and install a newer version of pip that doesn't rely on IncompleteRead, or package Rally into a virtualenv so that it can get the versions of dependencies it needs without replacing the older version of requests whose behavior this version of pip relies on.

**Comment by kamidzi** [comment]
I like the virtualenv approach, though I wonder whether we shouldn't proceed a step further and just make it a deb?

**Comment by erhudy** [comment]
I found that @cloudm2 had already anticipated this but the line to install the upgraded pip was commented out. Uncommented it and rebuilt and all was well.

**Comment by erhudy** [comment]
Filed #585 to fix this.
