### ISSUE TITLE
networking.rb assumes vagrant data structures exist in nodes objects

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#641]
A non-vagrant build encountered this error:

```
* template[/etc/ssh/sshd_config] action create
    
    ================================================================================
    Error executing action `create` on resource 'template[/etc/ssh/sshd_config]'
    ================================================================================
    
    Chef::Mixin::Template::TemplateError
    ------------------------------------
    undefined method `[]' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc/recipes/networking.rb
    
     30: template "/etc/ssh/sshd_config" do
     31:     source "sshd_config.erb"
     32:     mode 00644
     33:     notifies :restart, "service[ssh]", :immediately
     34: end
     35: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/bcpc/recipes/networking.rb:30:in `from_file'
    
    template("/etc/ssh/sshd_config") do
      action "create"
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/etc/ssh/sshd_config"
      backup 5
      atomic_update true
      source "sshd_config.erb"
      declared_type :template
      cookbook_name "bcpc"
      recipe_name "networking"
      mode 420
    end
    
    Template Context:
    -----------------
    on line #11
      9: # Use these options to restrict which interfaces/protocols sshd will bind to
     10: #ListenAddress ::
     11: <% if node['bcpc']['vagrant']['nat_ip'] %>
     12: ListenAddress <%= node['bcpc']['vagrant']['nat_ip'] %>
     13: <% end %>
    
Recipe: bcpc::cpupower
  * service[cpufrequtils] action restart
    - restart service service[cpufrequtils]
Recipe: ntp::default
  * service[ntp] action restart
    - restart service service[ntp]
Recipe: ntp::apparmor
  * service[apparmor] action restart
    - restart service service[apparmor]

Running handlers:
[2015-06-12T11:13:12-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-12T11:13:12-04:00] ERROR: Exception handlers complete
[2015-06-12T11:13:12-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 58 resources updated in 112.517713984 seconds
[2015-06-12T11:13:12-04:00] ERROR: 

Chef::Mixin::Template::TemplateError (undefined method `[]' for nil:NilClass) on line #11:

  9: # Use these options to restrict which interfaces/protocols sshd will bind to
 10: #ListenAddress ::
 11: <% if node['bcpc']['vagrant']['nat_ip'] %>
 12: ListenAddress <%= node['bcpc']['vagrant']['nat_ip'] %>
 13: <% end %>

  (erubis):11:in `block in evaluate'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/template.rb:114:in `_render_template'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/template.rb:100:in `render_template'
  /opt/chef/embedded/apps/chef/lib/chef/provider/template/content.rb:43:in `file_for_provider'
  /opt/chef/embedded/apps/chef/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
  /opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:459:in `tempfile'
  /opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:337:in `do_generate_content'
  /opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:148:in `action_create'
  /opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /opt/chef/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:449:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:51:in `load'
  /usr/bin/chef-client:51:in `<main>'
```

**Comment by erhudy** [comment]
Fixed in #642.
