### ISSUE TITLE
dns_fill.py fails when processing orphaned instances

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#809]
In the case where an instance is created, float attached, then the corresponding project is deleted, `dns_fill.py` will error out without processing all the necessary records. The error appears as below:

```
Traceback (most recent call last):
  File "/usr/local/bin/dns_fill.py", line 129, in <module>
    args.func(args)
  File "/usr/local/bin/dns_fill.py", line 107, in c_run
    nova_rows = dnsp.generate_records_from_vms()
  File "/usr/local/bin/dns_fill.py", line 61, in generate_records_from_vms
    tenant = self.keystone.tenants.get(tid)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/tenants.py", line 83, in get
    return self._get("/tenants/%s" % tenant_id, "tenant")
  File "/usr/lib/python2.7/dist-packages/keystoneclient/base.py", line 136, in _get
    resp, body = self.client.get(url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 164, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 200, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 89, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/utils.py", line 318, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/session.py", line 389, in request
    raise exceptions.from_response(resp, method, url)
keystoneclient.openstack.common.apiclient.exceptions.NotFound: Could not find project: 771dc271db654194bb0b7e220f07a2e8 (HTTP 404) (Request-ID: req-5a4a08e1-daee-4016-b34a-0245ab26d071)
```

**Comment by kamidzi** [comment]
btw, original issue reported by @kelvk on another system.
