### ISSUE TITLE
Changing a security group does not correctly refresh rules for subscribed instances

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#826]
This traceback occurs in nova-compute.log when an existing security group is edited:
```
2015-09-16 21:04:23.973 18547 ERROR oslo_messaging.rpc.dispatcher [req-098d6981-8348-460d-9fd8-cc7b04504c2c 96d465eb2535443f95e7efcd05276283 a5f9a733bbc6438e83ab79260e37f276 - - -] Exception during message handling: 'metadata'
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     executor_callback))
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     executor_callback)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 6772, in refresh_instance_security_rules
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     return self.manager.refresh_instance_security_rules(ctxt, instance)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 434, in decorated_function
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     args = (_load_instance(args[0]),) + args[1:]
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 425, in _load_instance
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     expected_attrs=metas)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/objects/instance.py", line 506, in _from_db_object
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     instance['metadata'] = utils.instance_meta(db_inst)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/utils.py", line 817, in instance_meta
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     if isinstance(instance['metadata'], dict):
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher KeyError: 'metadata'
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher 
```

**Comment by erhudy** [comment]
https://bugs.launchpad.net/nova/+bug/1484738

**Comment by erhudy** [comment]
Will backport patch from https://review.openstack.org/#/c/222023/. We're already modifying nova/compute/manager.py in another patch, unfortunately (https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/recipes/nova-work.rb#L42-L71), so the patch for this issue will be ordered to run after the first patch. Not ideal, obviously, but it's important to restore this functionality to users.
